[package]
name = "ocipa/accord"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fastsignal = "lucasmzreal/fastsignal@10.1.0"
testez = "roblox/testez@0.4.1"