[package]
name = "ocipa/accord"
version = "0.13.1"
license = "MIT"
authors = ["Ocipa <ocipamail@gmail.com>"]
description = "https://github.com/Ocipa/accord"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    "*.spec.lua", "*.spec.luau", "README.md", "assets",
    ".luaurc", ".gitignore", "aftman.toml", "selene.toml",
    "test.project.json", "sourcemap.json"
]

[dependencies]
