[package]
name = "ocipa/accord"
version = "0.10.0"
license = "MIT"
authors = ["Ocipa <ocipamail@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fastsignal = "lucasmzreal/fastsignal@10.1.0"