[package]
name = "ocipa/accord"
version = "0.11.0"
license = "MIT"
authors = ["Ocipa <ocipamail@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    "*.spec.lua", "test*", "README.md", "modules",
    ".gitmodules","assets", "*rbxl*"
]

[dependencies]
fastsignal = "lucasmzreal/fastsignal@10.1.0"
signal = "sleitnick/signal@1.2.1"